const Shop = () => {
    return (
        <>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae officiis architecto accusamus iusto, ipsa quod excepturi quos provident voluptates eos recusandae tenetur quia explicabo fugiat voluptas sed veniam, numquam est.
            Mollitia laudantium architecto, ducimus aut minus cum cupiditate tenetur? Iusto at magni assumenda. Qui nam, neque rerum corporis suscipit, assumenda voluptates tempora ipsum unde illum exercitationem ea eveniet, recusandae impedit.
            Repudiandae numquam velit facere rerum alias similique, dicta quo nobis neque dolore! Sit minima delectus sed fugit in necessitatibus beatae voluptatem! Officia ducimus nostrum cupiditate quos voluptatibus reprehenderit molestiae porro.
            Delectus cum necessitatibus quod amet adipisci placeat maxime iste error ratione explicabo, accusamus veniam laborum sit ducimus, assumenda itaque at in? Incidunt iure nulla praesentium, deleniti hic amet quas velit.
            Iste consequuntur dignissimos officia molestias. Non excepturi fugit obcaecati! Ea quos velit, voluptatibus maxime illo placeat maiores quia omnis ullam alias natus nisi explicabo molestiae! Facere consectetur temporibus ut saepe.
            Ipsam repellat vero asperiores fugiat repudiandae id corrupti quaerat omnis dignissimos harum laboriosam eaque officiis sint iusto minus temporibus voluptate molestias nemo at, praesentium eum. Quo placeat sapiente consectetur magni?
            Dolor ex libero rem quaerat! Commodi molestiae nesciunt, veniam ea, pariatur ipsum eos reprehenderit labore vero aliquid alias officia, quidem autem numquam aliquam consequuntur id neque nisi ex nobis animi!
            Soluta nulla veritatis itaque ipsa iusto alias quibusdam aperiam, voluptas blanditiis odio magni numquam eveniet est animi, adipisci dolorem doloremque nemo quo repudiandae incidunt aliquid. Optio porro doloremque iusto voluptatum?
            Numquam, officia sapiente quam at doloremque, qui vitae mollitia cumque ea debitis, reprehenderit veritatis hic voluptates? Accusantium dolor at obcaecati beatae esse earum. Sed doloremque aut maxime eum labore velit.
            Minima labore sunt quod quibusdam voluptate, aliquid eius. Sint fugit ipsa fuga quas sequi ducimus, laudantium exercitationem molestias porro sit nesciunt vero tempora, blanditiis, nulla facere ullam corporis dolores aliquid.
            Labore velit doloribus cupiditate ipsum expedita possimus excepturi odio nobis dolores harum vitae autem repudiandae neque ipsa veniam, quod, eligendi assumenda, laborum dicta sunt in fuga commodi? Provident, sequi. A.
            Quidem harum quisquam cum. Laudantium doloribus sit temporibus, omnis laboriosam, adipisci soluta, culpa delectus incidunt eum error quaerat? Doloremque ipsa quidem quae fugiat at ipsum nulla vitae non obcaecati dolor.
            Odit dolores tempora ratione, vitae minima exercitationem repellat nulla debitis numquam dolorem distinctio soluta reprehenderit suscipit, possimus aspernatur similique aliquam animi minus beatae voluptatem laudantium hic consectetur. Voluptatibus, eveniet incidunt.
            Voluptas aperiam a pariatur rem quia impedit corporis officia provident earum blanditiis tenetur voluptates nam, incidunt sequi et saepe. Ducimus nam hic, velit cum incidunt nesciunt earum officiis quaerat quos.
            Inventore minima accusamus molestias quaerat eos quam libero, quos totam reprehenderit dicta pariatur illo culpa omnis quisquam facere perferendis quo sint consectetur dolorem. Laborum temporibus, iste assumenda numquam nemo illum.
            Tempora facere accusamus voluptatum dolore quia nostrum, rem beatae aliquam illum odit neque, ab nesciunt omnis doloremque, deleniti debitis quisquam aperiam hic obcaecati ipsum cupiditate porro optio similique modi. Sapiente?
            Odit omnis exercitationem molestias excepturi aut, magnam nisi sit dolor impedit maxime, perspiciatis aliquam quia, placeat inventore. Rerum architecto tenetur voluptates repellat inventore. Accusantium provident neque sunt veniam nisi ex.
            Sint itaque eos amet quas in deserunt repellat numquam illo voluptatum natus quos vel iure doloribus excepturi veniam voluptas earum perspiciatis, officiis id, tenetur laborum quo! Ratione non vero totam!
            Esse, atque unde officiis possimus eum dolor suscipit? Quod tenetur, expedita assumenda cumque labore quis saepe nihil repellendus nam odio rerum, porro sed in vero ipsum illum eius ut. Harum!
            Labore magnam molestias quisquam esse recusandae, deserunt dolor architecto optio aspernatur saepe doloribus, excepturi at a nisi ex qui ad minima cum maiores consequatur temporibus vitae nihil quae maxime. Praesentium?
            Labore tenetur perferendis quidem officiis, possimus fuga sed eos atque repudiandae accusamus deleniti inventore cum temporibus, dolores exercitationem quam alias! Repellendus laborum officia inventore commodi excepturi cum nam consequatur eius.
            Quisquam porro excepturi corrupti blanditiis voluptatum nulla omnis. Adipisci doloremque aperiam fugiat placeat dignissimos soluta incidunt reprehenderit molestiae dolore, officia suscipit repudiandae quae, officiis quibusdam libero esse id dicta numquam!
            Esse deserunt laborum est amet praesentium blanditiis in repellat, voluptatum facere fugit illum ut. Saepe hic earum laboriosam dolor, ab cumque! Eligendi quibusdam voluptates, aut eaque laboriosam cumque asperiores. Vero.
            Sed, aliquid ab quibusdam iste itaque totam ad sapiente quos, optio vitae est voluptatibus, tempore sit nam quaerat sint? Dolor aliquam iusto repellendus et suscipit amet eaque tempore libero nemo.
            Autem repellat amet laborum quo qui illo fugit excepturi unde laboriosam rem ducimus cupiditate adipisci dignissimos commodi quisquam omnis cumque dicta ipsam, vero explicabo eaque placeat modi ipsum. Quod, ducimus?
            Et eligendi, enim praesentium accusantium numquam doloremque deserunt assumenda obcaecati at, dolore blanditiis a mollitia accusamus? Ab nam error ipsa sapiente adipisci, deleniti, animi rem quibusdam, sed ratione aliquam sint.
            Fugiat aliquid pariatur quaerat. Suscipit, animi iure officia obcaecati quos porro impedit quibusdam. Quae tenetur placeat amet inventore accusamus temporibus voluptatum officia delectus? Repudiandae eum totam corrupti, ipsam voluptatem adipisci!
            Voluptate temporibus, itaque odit corrupti assumenda voluptates sit, iure quis minima voluptas nobis laboriosam illo. A hic, excepturi sapiente voluptatum est necessitatibus odit quis cum ex quas error nulla possimus.
            Consectetur ducimus odit tenetur debitis et officiis ipsum placeat voluptas velit amet, aperiam deleniti laborum distinctio eius magnam, quidem dolores error id blanditiis nemo nesciunt at assumenda! Quibusdam, recusandae expedita!
            Dolorum deleniti inventore, tempora iure velit obcaecati dolore consectetur temporibus vero voluptate repellat possimus maxime error minus sed nobis distinctio iste, necessitatibus beatae recusandae itaque tempore adipisci? Aperiam, modi maiores?
            Numquam vel ratione iste suscipit illum officiis magnam ex dolorem eius quisquam corrupti nobis tempore, esse officia architecto perferendis nihil aut. Similique tenetur quia dolor quam dolore facilis nulla accusantium.
            Aliquid asperiores explicabo reprehenderit deserunt qui optio impedit debitis eos ad iusto facere fugit, tenetur sint assumenda aliquam quos minus consequatur hic sequi odit earum itaque! Dolorum dicta id suscipit.
            Sequi nam ratione fugit consectetur iste iure provident similique, laborum, dolore id quaerat, deserunt placeat. Quas eius ratione aspernatur quos soluta, sed odit laborum adipisci! Minima facere a sit explicabo?
            Ipsum ratione sunt placeat corporis voluptatibus accusamus illo nihil eaque pariatur eligendi dolor, assumenda facilis quo provident sequi saepe unde possimus veniam laboriosam ullam deleniti dolore reiciendis. Ea, dolor? Optio!
            Nobis incidunt error neque repudiandae amet corrupti, eveniet accusantium, beatae quis nesciunt voluptas recusandae doloribus! Aliquid officiis voluptate quam debitis natus totam dolore nobis, cupiditate ipsam odit autem laudantium dolorem.
            Modi, saepe doloribus ullam vitae totam et, quia deleniti nisi omnis sapiente magnam! Illo dolorum error autem perferendis architecto voluptatem similique sint placeat nulla ullam, aut hic odit numquam aspernatur?
            Incidunt beatae totam cupiditate maxime voluptate cumque similique laboriosam nihil dicta ullam voluptatem repellat, inventore laborum! Fugiat voluptatibus voluptates qui illo non nemo tempore pariatur voluptas similique eum. Consectetur, eligendi.
            Soluta natus quo, numquam voluptatibus iusto labore corporis odio perspiciatis non eveniet magnam ratione. Illum libero debitis sit deleniti odio quia nam, fugiat impedit suscipit at totam, provident ad. Hic!
            Temporibus ab blanditiis velit aperiam necessitatibus modi eveniet minima at ipsam possimus aspernatur dolor, in animi veritatis corrupti accusantium impedit libero porro. Voluptatibus odit quam magni, amet impedit aspernatur ex.
            Nihil ipsam cupiditate voluptatum possimus quisquam perspiciatis deleniti tempora, nulla fugit aliquid adipisci explicabo nostrum sapiente mollitia distinctio aperiam quasi enim accusamus, repudiandae ducimus saepe vel corrupti. Voluptate, ea dolorum?
            Repellat porro ea a asperiores laborum sint repudiandae voluptates iusto iste dolores temporibus quo praesentium et tempore nulla, similique obcaecati. Libero, magnam asperiores. Impedit facilis adipisci porro dolore quidem alias.
            Vero corporis distinctio consectetur. Velit quibusdam, labore ut placeat sapiente asperiores fugiat sint nesciunt ex quam necessitatibus fuga. Accusantium similique dolorum enim, quos totam accusamus aliquid nobis quam quis veniam?
            Impedit itaque et rerum, consectetur hic omnis voluptatum, in dignissimos inventore ipsa eum velit, culpa autem nobis? Quos consequuntur ipsa praesentium, cum veniam tempore cupiditate. Facere inventore perspiciatis nemo totam!
            Reiciendis cumque odit consequuntur, id accusantium placeat aliquid itaque neque natus quia quidem, quasi tempore atque ut facilis molestias dicta dolor amet distinctio qui veritatis! Laborum animi necessitatibus accusamus qui!
            Et, accusantium perspiciatis adipisci at quas mollitia non id fuga iste maiores sunt vitae in quam, incidunt natus exercitationem impedit, ex porro. Maxime aliquid minima cupiditate optio illo, amet aliquam.
            Sequi atque tempora quos quod repudiandae, autem nostrum, delectus laboriosam animi necessitatibus molestias sint quia. Ea, id sed alias facere cum quisquam minima inventore maxime delectus tenetur modi rerum temporibus.
            Eum rerum soluta dolor ducimus incidunt. Repellendus quae, alias consequuntur tempora laborum mollitia nostrum tenetur totam provident enim ad ullam facilis sunt maiores facere. Expedita, deserunt? Non repellendus perferendis adipisci.
            Nesciunt illo recusandae, laboriosam facilis eum soluta sint fuga cupiditate distinctio minus mollitia repellat adipisci rem dolorum nostrum quos, atque earum voluptatibus et ut tempora numquam nobis? Suscipit, distinctio facilis.
            Quod necessitatibus rem provident deserunt exercitationem consequatur. Sapiente perferendis tenetur cupiditate distinctio voluptatum pariatur deserunt corrupti? Reprehenderit qui nulla animi ad illum cumque nam vero, sint a laudantium commodi excepturi.
            Dolorem, quae illo. Libero repudiandae aspernatur exercitationem quis excepturi ducimus minus amet quasi! Distinctio minus alias labore consequatur delectus, maxime quia consectetur recusandae tempore laboriosam aut porro hic modi rem.
        </>
    )
}

export default Shop